package ChemLab101.ChemLab101;
public class TableOfElements {
    private Elements[] elements;

    public TableOfElements() {
        elements = new Elements[118];
        elements[0] = new Elements("Hydrogen", "H", 1, 1.008, "Gas", "Nonmetal", "Hydrogen is a chemical element with symbol H and atomic number 1. With a standard atomic weight of 1.008, hydrogen is the lightest element in the periodic table.");
        elements[1] = new Elements("Helium", "He", 2, 4.002602, "Gas", "Noble Gas", "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas that heads the noble gas group in the periodic table.");
        elements[2] = new Elements("Lithium", "Li", 3, 6.94, "Solid", "Alkali Metal", "Lithium is a chemical element with symbol Li and atomic number 3. It is a soft, silvery-white alkali metal.");
        elements[3] = new Elements("Beryllium", "Be", 4, 9.0121831, "Solid", "Alkaline Earth Metal", "Beryllium is a chemical element with symbol Be and atomic number 4. It is a relatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei that have collided with cosmic rays.");
        elements[4] = new Elements("Boron", "B", 5, 10.81, "Solid", "Metalloid", "Boron is a chemical element with symbol B and atomic number 5. Produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in the Solar system and in the Earth's crust.");
        elements[5] = new Elements("Carbon", "C", 6, 12.011, "Solid", "Nonmetal", "Carbon is a chemical element with symbol C and atomic number 6. It is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds.");
        elements[6] = new Elements("Nitrogen", "N", 7, 14.007, "Gas", "Nonmetal", "Nitrogen is a chemical element with symbol N and atomic number 7. It was first discovered and isolated by Scottish physician Daniel Rutherford in 1772.");
        elements[7] = new Elements("Oxygen", "O", 8, 15.999, "Gas", "Nonmetal", "Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group in the periodic table, a highly reactive nonmetal, and an oxidizing agent that readily forms oxides with most elements as well as with other compounds.");
        elements[8] = new Elements("Fluorine", "F", 9, 18.998403163, "Gas", "Halogen", "Fluorine is a chemical element with symbol F and atomic number 9. It is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions.");
        elements[9] = new Elements("Neon", "Ne", 10, 20.1797, "Gas", "Noble Gas", "Neon is a chemical element with symbol Ne and atomic number 10. It is a noble gas.");
        elements[10] = new Elements("Sodium", "Na", 11, 22.98976928, "Solid", "Alkali Metal", "Sodium is a chemical element with symbol Na and atomic number 11. It is a soft, silvery-white, highly reactive metal.");
        elements[11] = new Elements("Magnesium", "Mg", 12, 24.305, "Solid", "Alkaline Earth Metal", "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column (group 2, or alkaline earth metals) of the periodic table: all group 2 elements have the same electron configuration in the outer electron shell and a similar crystal structure.");
        elements[12] = new Elements("Aluminum", "Al", 13, 26.9815385, "Solid", "Post-Transition Metal", "Aluminium is a chemical element with symbol Al and atomic number 13. It is a silvery-white, soft, nonmagnetic and ductile metal in the boron group.");
        elements[13] = new Elements("Silicon", "Si", 14, 28.085, "Solid", "Metalloid", "Silicon is a chemical element with symbol Si and atomic number 14. It is a hard and brittle crystalline solid with a blue-grey metallic lustre; and it is a tetravalent metalloid and semiconductor.");
        elements[14] = new Elements("Phosphorus", "P", 15, 30.973761998, "Solid", "Nonmetal", "Phosphorus is a chemical element with symbol P and atomic number 15. Elemental phosphorus exists in two major forms, white phosphorus and red phosphorus, but because it is highly reactive, phosphorus is never found as a free element on Earth.");
        elements[15] = new Elements("Sulfur", "S", 16, 32.06, "Solid", "Nonmetal", "Sulfur or sulphur is a chemical element with symbol S and atomic number 16. It is abundant, multivalent, and nonmetallic.");
        elements[16] = new Elements("Chlorine", "Cl", 17, 35.45, "Gas", "Halogen", "Chlorine is a chemical element with symbol Cl and atomic number 17. The second-lightest of the halogens, it appears between fluorine and bromine in the periodic table and its properties are mostly intermediate between them.");
        elements[17] = new Elements("Argon", "Ar", 18, 39.948, "Gas", "Noble Gas", "Argon is a chemical element with symbol Ar and atomic number 18. It is in group 18 of the periodic table and is a noble gas.");
        elements[18] = new Elements("Potassium", "K", 19, 39.0983, "Solid", "Alkali Metal", "Potassium is a chemical element with symbol K (from Neo-Latin kalium) and atomic number 19. It was first isolated from potash, the ashes of plants, from which its name derives.");
        elements[19] = new Elements("Calcium", "Ca", 20, 40.078, "Solid", "Alkaline Earth Metal", "Calcium is a chemical element with symbol Ca and atomic number 20. An alkaline earth metal, calcium is a reactive metal that forms a dark oxide-nitride layer when exposed to air.");
        elements[20] = new Elements("Scandium", "Sc", 21, 44.955908, "Solid", "Transition Metal", "Scandium is a chemical element with symbol Sc and atomic number 21. A silvery-white metallic d-block element, it has historically been classified as a rare-earth element, together with yttrium and the lanthanides.");
        elements[21] = new Elements("Titanium", "Ti", 22, 47.867, "Solid", "Transition Metal", "Titanium is a chemical element with symbol Ti and atomic number 22. It is a lustrous transition metal with a silver color, low density, and high strength.");
        elements[22] = new Elements("Vanadium", "V", 23, 50.9415, "Solid", "Transition Metal", "Vanadium is a chemical element with symbol V and atomic number 23. It is a hard, silvery-grey, ductile, malleable transition metal.");
        elements[23] = new Elements("Chromium", "Cr", 24, 51.9961, "Solid", "Transition Metal", "Chromium is a chemical element with symbol Cr and atomic number 24. It is the first element in group 6.");
        elements[24] = new Elements("Manganese", "Mn", 25, 54.938044, "Solid", "Transition Metal", "Manganese is a chemical element with symbol Mn and atomic number 25. It is not found as a free element in nature; it is often found in minerals in combination with iron.");
        elements[25] = new Elements("Iron", "Fe", 26, 55.845, "Solid", "Transition Metal", "Iron is a chemical element with symbol Fe (from Latin: ferrum) and atomic number 26. It is a metal that belongs to the first transition series and group 8 of the periodic table.");
        elements[26] = new Elements("Cobalt", "Co", 27, 58.933194, "Solid", "Transition Metal", "Cobalt is a chemical element with symbol Co and atomic number 27. Like nickel, cobalt is found in the Earth's crust only in chemically combined form, save for small deposits found in alloys of natural meteoric iron.");
        elements[27] = new Elements("Nickel", "Ni", 28, 58.6934, "Solid", "Transition Metal", "Nickel is a chemical element with symbol Ni and atomic number 28. It is a silvery-white lustrous metal with a slight golden tinge.");
        elements[28] = new Elements("Copper", "Cu", 29, 63.546, "Solid", "Transition Metal", "Copper is a chemical element with symbol Cu (from Latin: cuprum) and atomic number 29. It is a soft, malleable, and ductile metal with very high thermal and electrical conductivity.");
        elements[29] = new Elements("Zinc", "Zn", 30, 65.38, "Solid", "Transition Metal", "Zinc is a chemical element with symbol Zn and atomic number 30. It is the first element in group 12 of the periodic table.");
        elements[30] = new Elements("Gallium", "Ga", 31, 69.723, "Solid", "Post-Transition Metal", "Gallium is a chemical element with symbol Ga and atomic number 31. It is in group 13 of the periodic table, and thus has similarities to the other metals of the group, aluminium, indium, and thallium.");
        elements[31] = new Elements("Germanium", "Ge", 32, 72.63, "Solid", "Metalloid", "Germanium is a chemical element with symbol Ge and atomic number 32. It is a lustrous, hard, grayish-white metalloid in the carbon group, chemically similar to its group neighbors tin and silicon.");
        elements[32] = new Elements("Arsenic", "As", 33, 74.921595, "Solid", "Metalloid", "Arsenic is a chemical element with symbol As and atomic number 33. Arsenic occurs in many minerals, usually in combination with sulfur and metals, but also as a pure elemental crystal.");
        elements[33] = new Elements("Selenium", "Se", 34, 78.971, "Solid", "Nonmetal", "Selenium is a chemical element with symbol Se and atomic number 34. It is a nonmetal (more rarely considered a metalloid) with properties that are intermediate between the elements above and below in the periodic table, sulfur and tellurium, and also has similarities to arsenic.");
        elements[34] = new Elements("Bromine", "Br", 35, 79.904, "Liquid", "Halogen", "Bromine is a chemical element with symbol Br and atomic number 35. It is the third-lightest halogen, and is a fuming red-brown liquid at room temperature that evaporates readily to form a similarly coloured gas.");
        elements[35] = new Elements("Krypton", "Kr", 36, 83.798, "Gas", "Noble Gas", "Krypton is a chemical element with symbol Kr and atomic number 36. It is a member of group 18 (noble gases) elements.");
        elements[36] = new Elements("Rubidium", "Rb", 37, 85.4678, "Solid", "Alkali Metal", "Rubidium is a chemical element with symbol Rb and atomic number 37. Rubidium is a soft, silvery-white metallic element of the alkali metal group, with a standard atomic weight of 85.4678.");
        elements[37] = new Elements("Strontium", "Sr", 38, 87.62, "Solid", "Alkaline Earth Metal", "Strontium is a chemical element with symbol Sr and atomic number 38. An alkaline earth metal, strontium is a soft silver-white yellowish metallic element that is highly reactive chemically.");
        elements[38] = new Elements("Yttrium", "Y", 39, 88.90584, "Solid", "Transition Metal", "Yttrium is a chemical element with symbol Y and atomic number 39. It is a silvery-metallic transition metal chemically similar to the lanthanides and has often been classified as a rare-earth element.");
        elements[39] = new Elements("Zirconium", "Zr", 40, 91.224, "Solid", "Transition Metal", "Zirconium is a chemical element with symbol Zr and atomic number 40. The name zirconium is taken from the name of the mineral zircon (the word is related to Persian zargun (zircon; zar-gun, \"gold-like\" or \"as gold\")), the most important source of zirconium.");
        elements[40] = new Elements("Niobium", "Nb", 41, 92.90637, "Solid", "Transition Metal", "Niobium, formerly columbium, is a chemical element with symbol Nb (formerly Cb) and atomic number 41. It is a soft, grey, crystalline, ductile transition metal, often found in the minerals pyrochlore and columbite, hence the former name \"columbium\".");
        elements[41] = new Elements("Molybdenum", "Mo", 42, 95.95, "Solid", "Transition Metal", "Molybdenum is a chemical element with symbol Mo and atomic number 42. The name is from Neo-Latin molybdaenum, from Ancient Greek Μόλυβδος molybdos, meaning lead, since its ores were confused with lead ores.");
        elements[42] = new Elements("Technetium", "Tc", 43, 98, "Solid", "Transition Metal", "Technetium is a chemical element with symbol Tc and atomic number 43. It is the lightest element whose isotopes are all radioactive; none are stable, excluding the fully ionized state of 98Tc.");
        elements[43] = new Elements("Ruthenium", "Ru", 44, 101.07, "Solid", "Transition Metal", "Ruthenium is a chemical element with symbol Ru and atomic number 44. It is a rare transition metal belonging to the platinum group of the periodic table.");
        elements[44] = new Elements("Rhodium", "Rh", 45, 102.90550, "Solid", "Transition Metal", "Rhodium is a chemical element with symbol Rh and atomic number 45. It is a rare, silvery-white, hard, corrosion-resistant, and chemically inert transition metal.");
        elements[45] = new Elements("Palladium", "Pd", 46, 106.42, "Solid", "Transition Metal", "Palladium is a chemical element with symbol Pd and atomic number 46. It is a rare and lustrous silvery-white metal discovered in 1803 by William Hyde Wollaston.");
        elements[46] = new Elements("Silver", "Ag", 47, 107.8682, "Solid", "Transition Metal", "Silver is a chemical element with symbol Ag (from the Latin argentum, derived from the Proto-Indo-European h₂erǵ: \"shiny\" or \"white\") and atomic number 47.");
        elements[47] = new Elements("Cadmium", "Cd", 48, 112.414, "Solid", "Transition Metal", "Cadmium is a chemical element with symbol Cd and atomic number 48. This soft, silvery-white metal is chemically similar to the two other stable metals in group 12, zinc and mercury.");
        elements[48] = new Elements("Indium", "In", 49, 114.818, "Solid", "Post-Transition Metal", "Indium is a chemical element with symbol In and atomic number 49. It is a post-transition metal that makes up 0.21 parts per million of the Earth's crust.");
        elements[49] = new Elements("Tin", "Sn", 50, 118.710, "Solid", "Post-Transition Metal", "Tin is a chemical element with the symbol Sn (from Latin: stannum) and atomic number 50. It is a post-transition metal in group 14 of the periodic table.");
        elements[50] = new Elements("Antimony", "Sb", 51, 121.760, "Solid", "Metalloid", "Antimony is a chemical element with symbol Sb (from Latin: stibium) and atomic number 51. A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite (Sb2S3).");
        elements[51] = new Elements("Tellurium", "Te", 52, 127.60, "Solid", "Metalloid", "Tellurium is a chemical element with symbol Te and atomic number 52. It is a brittle, mildly toxic, rare, silver-white metalloid.");
        elements[52] = new Elements("Iodine", "I", 53, 126.90447, "Solid", "Halogen", "Iodine is a chemical element with symbol I and atomic number 53. The heaviest of the stable halogens, it exists as a lustrous, purple-black non-metallic solid at standard conditions that sublimes readily to form a violet gas.");
        elements[53] = new Elements("Xenon", "Xe", 54, 131.293, "Gas", "Noble Gas", "Xenon is a chemical element with symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas found in the Earth's atmosphere in trace amounts.");
        elements[54] = new Elements("Cesium", "Cs", 55, 132.90545196, "Solid", "Alkali Metal", "Cesium is a chemical element with symbol Cs and atomic number 55. It is a soft, silvery-golden alkali metal with a melting point of 28.5 °C (83.3 °F), which makes it one of only five elemental metals that are liquid at or near room temperature.");
        elements[55] = new Elements("Barium", "Ba", 56, 137.327, "Solid", "Alkaline Earth Metal", "Barium is a chemical element with symbol Ba and atomic number 56. It is the fifth element in group 2 and is a soft, silvery alkaline earth metal.");
        elements[56] = new Elements("Lanthanum", "La", 57, 138.90547, "Solid", "Lanthanide", "Lanthanum is a chemical element with symbol La and atomic number 57. It is a soft, ductile, silvery-white metal that tarnishes rapidly when exposed to air and is soft enough to be cut with a knife.");
        elements[57] = new Elements("Cerium", "Ce", 58, 140.116, "Solid", "Lanthanide", "Cerium is a chemical element with symbol Ce and atomic number 58. Cerium is a soft, ductile and silvery-white metal that tarnishes when exposed to air, and it is soft enough to be cut with a knife.");
        elements[58] = new Elements("Praseodymium", "Pr", 59, 140.90766, "Solid", "Lanthanide", "Praseodymium is a chemical element with symbol Pr and atomic number 59. It is the third member of the lanthanide series and is traditionally considered to be one of the rare-earth metals.");
        elements[59] = new Elements("Neodymium", "Nd", 60, 144.242, "Solid", "Lanthanide", "Neodymium is a chemical element with symbol Nd and atomic number 60. Neodymium belongs to the lanthanide series and is a rare-earth element.");
        elements[60] = new Elements("Promethium", "Pm", 61, 145, "Solid", "Lanthanide", "Promethium is a chemical element with symbol Pm and atomic number 61. All of its isotopes are radioactive; it is one of only two such elements that are followed in the periodic table by elements with stable forms, a distinction shared with technetium.");
        elements[61] = new Elements("Samarium", "Sm", 62, 150.36, "Solid", "Lanthanide", "Samarium is a chemical element with symbol Sm and atomic number 62. It is a moderately hard silvery metal that slowly oxidizes in air.");
        elements[62] = new Elements("Europium", "Eu", 63, 151.964, "Solid", "Lanthanide", "Europium is a chemical element with symbol Eu and atomic number 63. It was isolated in 1901 and is named after the continent of Europe. It is a moderately hard, silvery metal which readily oxidizes in air and water.");
        elements[63] = new Elements("Gadolinium", "Gd", 64, 157.25, "Solid", "Lanthanide", "Gadolinium is a chemical element with symbol Gd and atomic number 64. Gadolinium is a silvery-white metal when oxidation is removed. It is only slightly malleable and is a ductile rare-earth element.");
        elements[64] = new Elements("Terbium", "Tb", 65, 158.92535, "Solid", "Lanthanide", "Terbium is a chemical element with symbol Tb and atomic number 65. It is a silvery-white, rare earth metal that is malleable, ductile, and soft enough to be cut with a knife.");
        elements[65] = new Elements("Dysprosium", "Dy", 66, 162.500, "Solid", "Lanthanide", "Dysprosium is a chemical element with the symbol Dy and atomic number 66. It is a rare earth element with a metallic silver luster.");
        elements[66] = new Elements("Holmium", "Ho", 67, 164.93033, "Solid", "Lanthanide", "Holmium is a chemical element with symbol Ho and atomic number 67. Part of the lanthanide series, holmium is a rare-earth element.");
        elements[67] = new Elements("Erbium", "Er", 68, 167.259, "Solid", "Lanthanide", "Erbium is a chemical element with symbol Er and atomic number 68. A silvery-white solid metal when artificially isolated, natural erbium is always found in chemical combination with other elements.");
        elements[68] = new Elements("Thulium", "Tm", 69, 168.93422, "Solid", "Lanthanide", "Thulium is a chemical element with symbol Tm and atomic number 69. It is the thirteenth and third-last element in the lanthanide series.");
        elements[69] = new Elements("Ytterbium", "Yb", 70, 173.045, "Solid", "Lanthanide", "Ytterbium is a chemical element with symbol Yb and atomic number 70. It is the fourteenth and penultimate element in the lanthanide series, which is the basis of the relative stability of its +2 oxidation state.");
        elements[70] = new Elements("Lutetium", "Lu", 71, 174.9668, "Solid", "Lanthanide", "Lutetium is a chemical element with symbol Lu and atomic number 71. It is a silvery white metal, which resists corrosion in dry air, but not in moist air.");
        elements[71] = new Elements("Hafnium", "Hf", 72, 178.49, "Solid", "Transition Metal", "Hafnium is a chemical element with symbol Hf and atomic number 72. A lustrous, silvery gray, tetravalent transition metal, hafnium chemically resembles zirconium and is found in many zirconium minerals.");
        elements[72] = new Elements("Tantalum", "Ta", 73, 180.94788, "Solid", "Transition Metal", "Tantalum is a chemical element with symbol Ta and atomic number 73. Previously known as tantalium, its name comes from Tantalus, a villain from Greek mythology.");
        elements[73] = new Elements("Tungsten", "W", 74, 183.84, "Solid", "Transition Metal", "Tungsten, or wolfram, is a chemical element with symbol W and atomic number 74. The name tungsten comes from the former Swedish name for the tungstate mineral scheelite, tung sten or \"heavy stone\".");
        elements[74] = new Elements("Rhenium", "Re", 75, 186.207, "Solid", "Transition Metal", "Rhenium is a chemical element with symbol Re and atomic number 75. It is a silvery-gray, heavy, third-row transition metal in group 7 of the periodic table.");
        elements[75] = new Elements("Osmium", "Os", 76, 190.23, "Solid", "Transition Metal", "Osmium is a chemical element with symbol Os and atomic number 76. It is a hard, brittle, bluish-white transition metal in the platinum group that is found as a trace element in alloys, mostly in platinum ores.");
        elements[76] = new Elements("Iridium", "Ir", 77, 192.217, "Solid", "Transition Metal", "Iridium is a chemical element with symbol Ir and atomic number 77. A very hard, brittle, silvery-white transition metal of the platinum group, iridium is the second-densest metal (after osmium) with a density of 22.56 g/cm3 as defined by experimental X-ray crystallography.");
        elements[77] = new Elements("Platinum", "Pt", 78, 195.084, "Solid", "Transition Metal", "Platinum is a chemical element with symbol Pt and atomic number 78. It is a dense, malleable, ductile, highly unreactive, precious, silverish-white transition metal.");
        elements[78] = new Elements("Gold", "Au", 79, 196.966569, "Solid", "Transition Metal", "Gold is a chemical element with symbol Au (from Latin: aurum) and atomic number 79, making it one of the higher atomic number elements that occur naturally.");
        elements[79] = new Elements("Mercury", "Hg", 80, 200.592, "Liquid", "Transition Metal", "Mercury is a chemical element with symbol Hg and atomic number 80. It is commonly known as quicksilver and was formerly named hydrargyrum.");
        elements[80] = new Elements("Thallium", "Tl", 81, 204.38, "Solid", "Post-Transition Metal", "Thallium is a chemical element with symbol Tl and atomic number 81. It is a gray post-transition metal that is not found free in nature.");
        elements[81] = new Elements("Lead", "Pb", 82, 207.2, "Solid", "Post-Transition Metal", "Lead is a chemical element with symbol Pb (from the Latin plumbum) and atomic number 82. It is a heavy metal that is denser than most common materials.");
        elements[82] = new Elements("Bismuth", "Bi", 83, 208.98040, "Solid", "Post-Transition Metal", "Bismuth is a chemical element with the symbol Bi and atomic number 83. It is a pentavalent post-transition metal and one of the pnictogens with chemical properties resembling its lighter homologs arsenic and antimony.");
        elements[83] = new Elements("Polonium", "Po", 84, 209, "Solid", "Post-Transition Metal", "Polonium is a chemical element with the symbol Po and atomic number 84. A rare and highly radioactive metal with no stable isotopes, polonium is chemically similar to selenium and tellurium, though its metallic character resembles that of its horizontal neighbors in the periodic table: thallium, lead, and bismuth.");
        elements[84] = new Elements("Astatine", "At", 85, 210, "Solid", "Halogen", "Astatine is a chemical element with the symbol At and atomic number 85. It is the rarest naturally occurring element in the Earth's crust, occurring only as the decay product of various heavier elements.");
        elements[85] = new Elements("Radon", "Rn", 86, 222, "Gas", "Noble Gas", "Radon is a chemical element with symbol Rn and atomic number 86. It is a radioactive, colorless, odorless, tasteless noble gas.");
        elements[86] = new Elements("Francium", "Fr", 87, 223, "Solid", "Alkali Metal", "Francium is a chemical element with symbol Fr and atomic number 87. It used to be known as eka-caesium and actinium K. It is the second-least electronegative element, behind only caesium, and is the second rarest naturally occurring element (after astatine).");
        elements[87] = new Elements("Radium", "Ra", 88, 226, "Solid", "Alkaline Earth Metal", "Radium is a chemical element with symbol Ra and atomic number 88. It is the sixth element in group 2 of the periodic table, also known as the alkaline earth metals.");
        elements[88] = new Elements("Actinium", "Ac", 89, 227, "Solid", "Actinide", "Actinium is a chemical element with the symbol Ac and atomic number 89. It was first isolated by Friedrich Oskar Giesel in 1902, who extracted it from pitchblende.");
        elements[89] = new Elements("Thorium", "Th", 90, 232.0377, "Solid", "Actinide", "Thorium is a weakly radioactive metallic chemical element with the symbol Th and atomic number 90. Thorium is silvery and tarnishes black when it is exposed to air, forming thorium dioxide; it is moderately hard, malleable, and has a high melting point.");
        elements[90] = new Elements("Protactinium", "Pa", 91, 231.03588, "Solid", "Actinide", "Protactinium is a chemical element with symbol Pa and atomic number 91. It is a dense, silvery-gray actinide metal which readily reacts with oxygen, water vapor and inorganic acids.");
        elements[91] = new Elements("Uranium", "U", 92, 238.02891, "Solid", "Actinide", "Uranium is a chemical element with symbol U and atomic number 92. It is a silvery-grey metal in the actinide series of the periodic table. A uranium atom has 92 protons and 92 electrons, of which 6 are valence electrons.");
        elements[92] = new Elements("Neptunium", "Np", 93, 237, "Solid", "Actinide", "Neptunium is a chemical element with the symbol Np and atomic number 93. A radioactive actinide metal, neptunium is the first transuranic element. Its position in the periodic table just after uranium, named after the planet Uranus, led to it being named after Neptune, the next planet beyond Uranus.");
        elements[93] = new Elements("Plutonium", "Pu", 94, 244, "Solid", "Actinide", "Plutonium is a radioactive chemical element with the symbol Pu and atomic number 94. It is an actinide metal of silvery-gray appearance that tarnishes when exposed to air, and forms a dull coating when oxidized.");
        elements[94] = new Elements("Americium", "Am", 95, 243, "Solid", "Actinide", "Americium is a synthetic chemical element with the symbol Am and atomic number 95. It is a transuranic member of the actinide series, in the periodic table located under the lanthanide element europium, and thus by analogy was named after the Americas.");
        elements[95] = new Elements("Curium", "Cm", 96, 247, "Solid", "Actinide", "Curium is a transuranic radioactive chemical element with symbol Cm and atomic number 96. This element of the actinide series was named after Marie and Pierre Curie – both were known for their research on radioactivity.");
        elements[96] = new Elements("Berkelium", "Bk", 97, 247, "Solid", "Actinide", "Berkelium is a transuranic radioactive chemical element with symbol Bk and atomic number 97. It is a member of the actinide and transuranium element series.");
        elements[97] = new Elements("Californium", "Cf", 98, 251, "Solid", "Actinide", "Californium is a radioactive metallic chemical element with symbol Cf and atomic number 98. The element was first made in 1950 at the University of California Radiation Laboratory in Berkeley, by bombarding curium with alpha particles (helium-4 ions).");
        elements[98] = new Elements("Einsteinium", "Es", 99, 252, "Solid", "Actinide", "Einsteinium is a synthetic element with the symbol Es and atomic number 99. It is the seventh transuranic element, and an actinide. Einsteinium was discovered as a component of the debris of the first hydrogen bomb explosion in 1952, and named after Albert Einstein.");
        elements[99] = new Elements("Fermium", "Fm", 100, 257, "Solid", "Actinide", "Fermium is a synthetic element with symbol Fm and atomic number 100. It is an actinide and the heaviest element that can be formed by neutron bombardment of lighter elements, and hence the last element that can be prepared in macroscopic quantities, although pure fermium metal has not yet been prepared.");
        elements[100] = new Elements("Mendelevium", "Md", 101, 258, "Solid", "Actinide", "Mendelevium is a synthetic element with chemical symbol Md (formerly Mv) and atomic number 101. A metallic radioactive transuranic element in the actinide series, it is the first element that currently cannot be produced in macroscopic quantities through neutron bombardment of lighter elements.");
        elements[101] = new Elements("Nobelium", "No", 102, 259, "Solid", "Actinide", "Nobelium is a synthetic chemical element with symbol No and atomic number 102. It is named in honor of Alfred Nobel, the inventor of dynamite and benefactor of science.");
        elements[102] = new Elements("Lawrencium", "Lr", 103, 266, "Solid", "Actinide", "Lawrencium is a synthetic chemical element with symbol Lr (formerly Lw) and atomic number 103. It is named in honor of Ernest Lawrence, inventor of the cyclotron, a device that was used to discover many artificial radioactive elements.");
        elements[103] = new Elements("Rutherfordium", "Rf", 104, 267, "Solid", "Transition Metal", "Rutherfordium is a synthetic chemical element with symbol Rf and atomic number 104, named in honor of physicist Ernest Rutherford. It is a synthetic element (an element that can be created in a laboratory but is not found in nature) and is radioactive; the most stable known isotope, 267Rf, has a half-life of approximately 1.3 hours.");
        elements[104] = new Elements("Dubnium", "Db", 105, 268, "Solid", "Transition Metal", "Dubnium is a synthetic chemical element with symbol Db and atomic number 105. Dubnium is highly radioactive: the most stable known isotope, dubnium-268, has a half-life of about 28 hours.");
        elements[105] = new Elements("Seaborgium", "Sg", 106, 269, "Solid", "Transition Metal", "Seaborgium is a synthetic element with symbol Sg and atomic number 106. It is named after the American nuclear chemist Glenn T. Seaborg. As a synthetic element, it can be created in a laboratory but is not found in nature.");
        elements[106] = new Elements("Bohrium", "Bh", 107, 270, "Solid", "Transition Metal", "Bohrium is a synthetic chemical element with symbol Bh and atomic number 107. It is named after Danish physicist Niels Bohr. As a synthetic element, it can be created in a laboratory but is not found in nature.");
        elements[107] = new Elements("Hassium", "Hs", 108, 277, "Solid", "Transition Metal", "Hassium is a synthetic chemical element with symbol Hs and atomic number 108. It is named after the German state of Hesse. It is a synthetic element and radioactive; the most stable known isotope, 269Hs, has a half-life of approximately 9.7 seconds.");
        elements[108] = new Elements("Meitnerium", "Mt", 109, 278, "Solid", "Transition Metal", "Meitnerium is a synthetic chemical element with symbol Mt and atomic number 109. It is an extremely radioactive synthetic element (an element that can be created in a laboratory but is not found in nature); the most stable known isotope, meitnerium-278, has a half-life of 7.6 seconds.");
        elements[109] = new Elements("Darmstadtium", "Ds", 110, 281, "Solid", "Transition Metal", "Darmstadtium is a synthetic chemical element with symbol Ds and atomic number 110. It is an extremely radioactive synthetic element. The most stable known isotope, darmstadtium-281, has a half-life of approximately 10 seconds.");
        elements[110] = new Elements("Roentgenium", "Rg", 111, 282, "Solid", "Transition Metal", "Roentgenium is a chemical element with symbol Rg and atomic number 111. It is an extremely radioactive synthetic element that can be created in a laboratory but is not found in nature.");
        elements[111] = new Elements("Copernicium", "Cn", 112, 285, "Solid", "Transition Metal", "Copernicium is a synthetic chemical element with symbol Cn and atomic number 112. It is an extremely radioactive element and can only be created in a laboratory.");
        elements[112] = new Elements("Nihonium", "Nh", 113, 286, "Solid", "Post-Transition Metal", "Nihonium is a synthetic chemical element with symbol Nh and atomic number 113. It is extremely radioactive; its most stable known isotope, nihonium-286, has a half-life of about 10 seconds.");
        elements[113] = new Elements("Flerovium", "Fl", 114, 289, "Solid", "Post-Transition Metal", "Flerovium is a superheavy artificial chemical element with symbol Fl and atomic number 114. It is an extremely radioactive synthetic element.");
        elements[114] = new Elements("Moscovium", "Mc", 115, 290, "Solid", "Post-Transition Metal", "Moscovium is a synthetic element with the symbol Mc and atomic number 115. It was first synthesized in 2003 by a joint team of Russian and American scientists at the Joint Institute for Nuclear Research (JINR) in Dubna, Russia.");
        elements[115] = new Elements("Livermorium", "Lv", 116, 293, "Solid", "Post-Transition Metal", "Livermorium is a synthetic chemical element with symbol Lv and atomic number 116. It is an extremely radioactive element that has only been created in the laboratory and has not been observed in nature.");
        elements[116] = new Elements("Tennessine", "Ts", 117, 294, "Solid", "Halogen", "Tennessine is a synthetic chemical element with symbol Ts and atomic number 117. It is the second-heaviest known element and the penultimate element of the 7th period of the periodic table.");
        elements[117] = new Elements("Oganesson", "Og", 118, 294, "Solid", "Noble Gas", "Oganesson is a synthetic chemical element with symbol Og and atomic number 118. It was first synthesized in 2002 at the Joint Institute for Nuclear Research (JINR) in Dubna, near Moscow, Russia.");
    }

    public void printElements() {
        for (int i = 0; i < elements.length; i++) {
            System.out.println(elements[i].toString());
        }
    }

    public void printAllSymbols() {
        for (int i = 0; i < elements.length; i++) {
            System.out.println(elements[i].getSymbol());
        }
    }

    public void printAllNames() {
        for (int i = 0; i < elements.length; i++) {
            System.out.println(elements[i].getName());
        }
    }
}
